#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

nitrogen --restore &
picom --no-fading-openclose &
numlockx &
wmname LG3D &
$HOME/.config/polybar/launch.sh

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         2
bspc config window_gap          10
bspc config top_padding         20
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config single_monocle       false
bspc config click_to_focus       true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true

#### BSPWM coloring ####
bspc config normal_border_color		  "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	  "#5e81ac"
bspc config presel_feedback_color	  "#5e81ac"
bspc config urgent_border_color 	  "#dd2727"


bspc rule -a Brave-browser desktop='^2'
bspc rule -a qBittorrent desktop='^7'
