#! /bin/sh

# Make sure bspwm removes all its rules for a clean restart
bspc rule -r "*"

pgrep -x sxhkd > /dev/null || sxhkd &
## autostart
xrdb -merge $HOME/.Xresources
numlockx on
$HOME/.config/polybar/launch.sh

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Brave-browser desktop='^2'
bspc rule -a discord desktop='^6' follow=on
bspc rule -a Pcmanfm desktop='^5'
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
